apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
        - name: nestjs-container
          image: yourusername/nestjs-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: 'postgres://user:password@postgres-service:5432/dbname'
            - name: REDIS_URL
              value: 'redis://redis-service:6379'
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  selector:
    app: nestjs-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
